Origin/fix hospitalisation&icu model
opensafely/immunosuppressant-meds-research pull request #110
Opened 2021-04-21 10:41 UTC by katiebechman

@AnnaB45 - here are the new files 003 define covariates & 202 cox models

2021-04-21 11:30 UTC, AnnaB45 commented
@katiebechman - would you be able to save the changed define covariates file as the same name as the previous one (000_define_covariates.do) rather than saving as a new file? This means that the changes between the current define covariates file and the updated one you've made will be really easy to review.

2021-04-21 11:42 UTC, AnnaB45 commented
@katiebechman  - on the cox models file, the current versions in the master branch remove the first loop (over the 13 different datasets) so that the models for each dataset can be run in parallel in the job server - which is much quicker. 
I think the changes you've made add this loop back in, is this for a particular reason? 

Looking at the code the models run against four outcomes:
- hospital admission date (with positive test within date restrictions)
- icu admission or death (with positive test within date restrictions based on hospital admissions flag)
- hospital admission date sensitivity analysis (with positive test but positive result can occur at anytime pre admission)
- icu admission sensitivity analysis (icu admission only with positive test within date restrictions)

These are on top of the two existing outcomes that don't need to be rerun (death and positive COVID test), is that right?

2021-04-21 13:07 UTC, katiebechman commented
@AnnaB45 I ahve uploaded baseline covariates saved as 000

2021-04-22 11:13 UTC, AnnaB45 commented on analysis/000_define_covariates.do
> +						 atopic_dermatitis					///
This doesn't needed to be added back in - we removed atopic_dermatitis from this study

2021-04-22 11:13 UTC, AnnaB45 commented on analysis/000_define_covariates.do
> -						 hospital_admission_date			///
This shouldn't be removed - need to include the hospital_admission_date as part of the data cleaning process

2021-04-22 11:14 UTC, AnnaB45 commented on analysis/000_define_covariates.do
> -rename hospital_admission_date_date		hospital_admission_date
This shouldn't be removed - need to include hospital admission as part of the data cleaning process

2021-04-22 11:14 UTC, AnnaB45 commented on analysis/000_define_covariates.do
> +						 atopic_dermatitis_date					///
This doesn't need to be added back in - removed atopic_dermatitis from the study definition

2021-04-22 11:14 UTC, AnnaB45 commented on analysis/000_define_covariates.do
> -						 hospital_admission_date				///
This needs to be included so can refer to hospital_admission_date later, so shouldn't be removed

2021-04-22 11:15 UTC, AnnaB45 commented on analysis/000_define_covariates.do
> +replace atopic_dermatitis =0 if hidradenitis_suppurativa_date > atopic_dermatitis_date & hidradenitis_suppurativa_date !=.
don't need to uncomment the atopic dermatitis cleaning as not included in the study definition

2021-04-22 11:16 UTC, AnnaB45 commented on analysis/000_define_covariates.do
> -						methotrexate_inj_6m_3m   ///
Shouldn't remove these as need to include methotrexate injectables in the standard systemic drugs groups

2021-04-22 11:16 UTC, AnnaB45 commented on analysis/000_define_covariates.do
> +gen standsys =1 if azathioprine_3m_0m >=1 | azathioprine_6m_3m >=1 | ciclosporin_3m_0m >=1 |ciclosporin_6m_3m >=1 | leflunomide_3m_0m >=1 |leflunomide_6m_3m >=1 | mercaptopurine_3m_0m >=1 |mercaptopu
Looks like methotrexate injectables removed here, need to keep these in

2021-04-22 11:17 UTC, AnnaB45 commented on analysis/000_define_covariates.do
> +gen standsys3m =1 if azathioprine_3m_0m >=1 | ciclosporin_3m_0m >=1 | leflunomide_3m_0m >=1 | mercaptopurine_3m_0m >=1 | methotrexate_3m_0m >=1 | methotrexate_hcd_3m_0m >=1 | mycophenolate_3m_0m >=1
Looks like methotrexate injectables removed here, need to keep these in

2021-04-22 11:18 UTC, AnnaB45 commented on analysis/000_define_covariates.do
> +replace standtnf3m =0 if adalimumab_3m_0m !=1 & certolizumab_3m_0m !=1 & etanercept_3m_0m !=1 & golimumab_3m_0m !=1 & infliximab_3m_0m !=1 & standsys3m ==1 & imid !=1
Is it right to add this extra condition here?

2021-04-22 11:18 UTC, AnnaB45 commented on analysis/000_define_covariates.do
> +replace standil233m =0 if ustekinumab_3m_0m !=1 & guselkumab_3m_0m !=1 & tildrakizumab_3m_0m !=1 & risankizumab_3m_0m !=1 & standsys3m ==1 & imid !=1
Is it right to add this extra condition here?

2021-04-22 11:18 UTC, AnnaB45 commented on analysis/000_define_covariates.do
> +replace standjaki3m =0 if baricitinib_3m_0m !=1 & tofacitinib_3m_0m !=1 & standsys3m ==1 & imid !=1
Is it right to add this extra condition here?

2021-04-22 11:19 UTC, AnnaB45 commented on analysis/000_define_covariates.do
> +replace standritux3m =0 if rituximab_3m_0m !=1 & standsys3m ==1 & imid !=1
Is it right to add this extra condition here?

2021-04-22 11:19 UTC, AnnaB45 commented on analysis/000_define_covariates.do
> -
Need to include this code block as removes patients on other high cost drugs from the standard systemic comparison group

2021-04-22 11:20 UTC, AnnaB45 commented on analysis/000_define_covariates.do
> -replace hospital_admission_date=hospital_admission_date+0.5 if hospital_admission_date==enter_date
Need to include this here as adding half day buffer to hospital admissions in same way as to other outcome variables

2021-04-22 11:22 UTC, AnnaB45 commented on analysis/000_define_covariates.do
> -format died_ons_date_covid died_ons_date_noncovid icu_admit_date_covid icu_or_death_covid_date hosp_admit_date_covid %td
Is this formatting for the outcome variables no longer required?

2021-04-22 11:26 UTC, AnnaB45 requested changes
@katiebechman - I've gone through the changes to the 000_define_covariates.do file and  most of the issues that need to be resolved are because you've added the new outcome variables on to an older version of the 000_define_covariates.do file then is currently in the master branch.

So the things to fix are to restore some of the previous changes that had been made - I've added comments where this is the case.

Let me know if you have any questions - happy to have a call.

2021-04-22 11:39 UTC, AnnaB45 requested changes
Some Qs on the naming of the icu outcome variable and the switching of $file to `f'

2021-04-22 11:39 UTC, AnnaB45 commented on analysis/202_cox_models.do
> +log using "$logdir/cox_models_$files", replace
Need to give the log a different name otherwise it'll overwrite the log from the other cox models (death and positive test)

2021-04-22 11:39 UTC, AnnaB45 commented on analysis/202_cox_models.do
> +		using $projectdir/output/data/cox_model_summary_$files, replace
Need to give the output files a different name then cox_model_summary_$files otherwise will overwrite existing cox model outputs for death and positive tests

2021-04-22 11:39 UTC, AnnaB45 commented on analysis/202_cox_models.do
> +egen stopicu = rmin(icu_or_death_covid_date diecensor)
Should this be called "stopicuordeath" so the outcome is clearer?

2021-04-22 11:39 UTC, AnnaB45 commented on analysis/202_cox_models.do
> +gen failicu = icu_or_death_covid
should this be called failicuordeath so the outcome is clearer?

2021-04-22 11:39 UTC, AnnaB45 commented on analysis/202_cox_models.do
> +gen exiticu = icu_or_death_covid
should this be called exiticuordeath so the outcome is clearer?

2021-04-22 11:39 UTC, AnnaB45 commented on analysis/202_cox_models.do
> +						local events_exposed .
Need to include the $files $`model` rather than `f` $`model` to allow the correct input data file to be referenced in the stata code - so would keep as in the previous version of the stata file

2021-04-22 11:39 UTC, AnnaB45 commented on analysis/202_cox_models.do
> +		}
Similar comment here as above - need to reference the input data files as $files rather than `f' - so would keep code as is in the previous version

2021-04-22 11:42 UTC, AnnaB45 reviewed
Q on whether should include all outcomes in one stata file for graphs (so not running one for deaths and one for evertything else), also about name of the "icu" variable

2021-04-22 11:42 UTC, AnnaB45 commented on analysis/302_survival_curves.do
> +egen stopsensicu_sens = rmin(icu_admit_date_covid_sens diecensor)
For simplicity - should this stata file also include the death outcome, so all graphs for outcomes run in the same file?
Also same comment on if the "stopicu" outcome should be changed to "stopicuordeath" so it's clear to others? (applies to the fail and exit variables below)

2021-04-22 12:21 UTC, katiebechman commented on analysis/000_define_covariates.do
> +						 atopic_dermatitis					///
yes

2021-04-22 12:21 UTC, katiebechman commented on analysis/000_define_covariates.do
> -						 hospital_admission_date			///
yes

2021-04-22 12:22 UTC, katiebechman commented on analysis/000_define_covariates.do
> -rename hospital_admission_date_date		hospital_admission_date
yes

2021-04-22 12:22 UTC, katiebechman commented on analysis/000_define_covariates.do
> +						 atopic_dermatitis_date					///
yes

2021-04-22 12:22 UTC, katiebechman commented on analysis/000_define_covariates.do
> -						 hospital_admission_date				///
yes

2021-04-22 12:22 UTC, katiebechman commented on analysis/000_define_covariates.do
> +replace atopic_dermatitis =0 if hidradenitis_suppurativa_date > atopic_dermatitis_date & hidradenitis_suppurativa_date !=.
yes

2021-04-22 12:23 UTC, katiebechman commented on analysis/000_define_covariates.do
> -						methotrexate_inj_6m_3m   ///
yes

2021-04-22 12:27 UTC, katiebechman commented on analysis/000_define_covariates.do
> +gen standsys =1 if azathioprine_3m_0m >=1 | azathioprine_6m_3m >=1 | ciclosporin_3m_0m >=1 |ciclosporin_6m_3m >=1 | leflunomide_3m_0m >=1 |leflunomide_6m_3m >=1 | mercaptopurine_3m_0m >=1 |mercaptopu
yes

2021-04-22 12:27 UTC, katiebechman commented on analysis/000_define_covariates.do
> +gen standsys3m =1 if azathioprine_3m_0m >=1 | ciclosporin_3m_0m >=1 | leflunomide_3m_0m >=1 | mercaptopurine_3m_0m >=1 | methotrexate_3m_0m >=1 | methotrexate_hcd_3m_0m >=1 | mycophenolate_3m_0m >=1
yes

2021-04-22 12:35 UTC, katiebechman commented on analysis/000_define_covariates.do
> +replace standtnf3m =0 if adalimumab_3m_0m !=1 & certolizumab_3m_0m !=1 & etanercept_3m_0m !=1 & golimumab_3m_0m !=1 & infliximab_3m_0m !=1 & standsys3m ==1 & imid !=1
no, this is already handled by the loop in line 703

2021-04-22 12:35 UTC, katiebechman commented on analysis/000_define_covariates.do
> +replace standil233m =0 if ustekinumab_3m_0m !=1 & guselkumab_3m_0m !=1 & tildrakizumab_3m_0m !=1 & risankizumab_3m_0m !=1 & standsys3m ==1 & imid !=1
no, this is already handled by the loop in line 703

2021-04-22 12:36 UTC, katiebechman commented on analysis/000_define_covariates.do
> +replace standjaki3m =0 if baricitinib_3m_0m !=1 & tofacitinib_3m_0m !=1 & standsys3m ==1 & imid !=1
no, this is already handled by the loop in line 703

2021-04-22 12:36 UTC, katiebechman commented on analysis/000_define_covariates.do
> +replace standritux3m =0 if rituximab_3m_0m !=1 & standsys3m ==1 & imid !=1
no, this is already handled by the loop in line 703

2021-04-22 12:36 UTC, katiebechman commented on analysis/000_define_covariates.do
> -
yes this loop needs to stay in

2021-04-22 12:37 UTC, katiebechman commented on analysis/000_define_covariates.do
> -replace hospital_admission_date=hospital_admission_date+0.5 if hospital_admission_date==enter_date
yes!

2021-04-22 12:41 UTC, katiebechman commented on analysis/000_define_covariates.do
> -format died_ons_date_covid died_ons_date_noncovid icu_admit_date_covid icu_or_death_covid_date hosp_admit_date_covid %td
no as far as i'm aware formatting is still required. Was it in the last version from James?

2021-04-22 12:50 UTC, katiebechman commented on analysis/202_cox_models.do
> +gen exiticu = icu_or_death_covid
made this change

2021-04-22 12:50 UTC, katiebechman commented on analysis/202_cox_models.do
> +gen failicu = icu_or_death_covid
made this change

2021-04-22 12:51 UTC, katiebechman commented on analysis/202_cox_models.do
> +						local events_exposed .
yes

2021-04-22 12:51 UTC, katiebechman commented on analysis/202_cox_models.do
> +		}
yes

2021-04-22 12:53 UTC, katiebechman commented on analysis/302_survival_curves.do
> +egen stopsensicu_sens = rmin(icu_admit_date_covid_sens diecensor)
yes i agree, i have now include death outcome and also changed icu to icuordeath

2021-04-22 14:10 UTC, AnnaB45 commented
Have moved changes to another branch/pull request so can close this one without merging

2021-04-22 14:10 UTC, closed without merging